import React, { useState, useEffect } from 'react';

interface InformConsoleProps {
  systemHealth?: any;
}

export const InformConsole: React.FC<InformConsoleProps> = ({ systemHealth }) => {
  const [notifications, setNotifications] = useState<any[]>([]);
  const [newNotification, setNewNotification] = useState('');
  const [notificationType, setNotificationType] = useState<'info' | 'warning' | 'error' | 'success'>('info');

  useEffect(() => {
    if (systemHealth) {
      // Auto-generate system health notifications
      const healthNotification = {
        id: Date.now(),
        type: systemHealth.status === 'healthy' ? 'success' : 'warning',
        message: `System health update: ${systemHealth.status}`,
        timestamp: new Date(),
        autoGenerated: true
      };
      setNotifications(prev => [healthNotification, ...prev.slice(0, 19)]); // Keep last 20
    }
  }, [systemHealth]);

  const addNotification = () => {
    if (newNotification.trim()) {
      const notification = {
        id: Date.now(),
        type: notificationType,
        message: newNotification,
        timestamp: new Date(),
        autoGenerated: false
      };
      setNotifications(prev => [notification, ...prev.slice(0, 19)]);
      setNewNotification('');
    }
  };

  const deleteNotification = (id: number) => {
    setNotifications(prev => prev.filter(notif => notif.id !== id));
  };

  const clearAllNotifications = () => {
    setNotifications([]);
  };

  const getNotificationIcon = (type: string) => {
    switch (type) {
      case 'success': return '✅';
      case 'warning': return '⚠️';
      case 'error': return '❌';
      case 'info': return 'ℹ️';
      default: return '📢';
    }
  };

  return (
    <div className="inform-console">
      <div className="console-header">
        <h3>Inform Console</h3>
        <div className="notification-input">
          <select
            value={notificationType}
            onChange={(e) => setNotificationType(e.target.value as any)}
            className="notification-type-select"
          >
            <option value="info">Info</option>
            <option value="success">Success</option>
            <option value="warning">Warning</option>
            <option value="error">Error</option>
          </select>
          <input
            type="text"
            value={newNotification}
            onChange={(e) => setNewNotification(e.target.value)}
            placeholder="Enter notification message..."
            onKeyPress={(e) => e.key === 'Enter' && addNotification()}
          />
          <button onClick={addNotification} className="btn-add">
            Add Notification
          </button>
        </div>
      </div>

      <div className="notifications-controls">
        <button onClick={clearAllNotifications} className="btn-clear">
          Clear All
        </button>
        <span className="notification-count">
          {notifications.length} notification(s)
        </span>
      </div>

      <div className="notifications-list">
        {notifications.map((notification) => (
          <div key={notification.id} className={`notification ${notification.type}`}>
            <div className="notification-header">
              <span className="notification-icon">
                {getNotificationIcon(notification.type)}
              </span>
              <span className="notification-time">
                {notification.timestamp.toLocaleTimeString()}
              </span>
              {notification.autoGenerated && (
                <span className="auto-generated">Auto</span>
              )}
            </div>
            <div className="notification-message">{notification.message}</div>
            <div className="notification-actions">
              <button 
                onClick={() => deleteNotification(notification.id)}
                className="btn-delete"
              >
                Delete
              </button>
            </div>
          </div>
        ))}
        {notifications.length === 0 && (
          <div className="no-notifications">
            No notifications yet. Add notifications to inform about system events.
          </div>
        )}
      </div>

      <div className="notification-stats">
        <h4>Notification Statistics</h4>
        <div className="stats-grid">
          <div className="stat">
            <span className="stat-label">Total:</span>
            <span className="stat-value">{notifications.length}</span>
          </div>
          <div className="stat">
            <span className="stat-label">Info:</span>
            <span className="stat-value">
              {notifications.filter(n => n.type === 'info').length}
            </span>
          </div>
          <div className="stat">
            <span className="stat-label">Warnings:</span>
            <span className="stat-value">
              {notifications.filter(n => n.type === 'warning').length}
            </span>
          </div>
          <div className="stat">
            <span className="stat-label">Errors:</span>
            <span className="stat-value">
              {notifications.filter(n => n.type === 'error').length}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}; 